#!/bin/bash
set -e

#TODO: The App Root should be defaulted inside of public. But we need to move the storage
#and stuff first.
rootdir="${APP_ROOT:-$(pwd)}"

echo "Root ${rootdir}"

# Make sure the storage directories exist and are writable by the webserver
mkdir "${rootdir}/bin/usr" || true
mkdir "${rootdir}/bin/usr/sessions" || true
mkdir "${rootdir}/bin/usr/uploads" || true

chown www-data: "${rootdir}/bin/usr/"
chown www-data: "${rootdir}/bin/usr/uploads"
chown www-data: "${rootdir}/bin/usr/sessions"

if [ -z ${DEBUG+x} ]; then
	export DEBUG=false
fi

# Run composer install. If the system is in production mode, we will optimize the 
# autoload and omit development artifacts. Otherwise, the normal autoload is generated
if [ "$DEBUG" = true ]; then
	composer install --no-interaction
fi

if ! [ -f "${rootdir}/.env" ]; then
	echo "No .env file found in ${rootdir}/ Creating default"
	cp ${rootdir}/.env.example ${rootdir}/.env
fi

if ! [ -f "${rootdir}/bin/settings/environments.php" ]; then
	echo "No bin/settings/environments.php file found in ${rootdir}/ Creating default"
	cp ${rootdir}/bin/settings/environments.php.sample ${rootdir}/bin/settings/environments.php
fi

wait-for-it ${DBSERVER:-mysql}:3306 -- echo 'MySQL is ready'

ls -la /etc/apache2/sites-enabled/

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
